# Generated by Django 4.2.6 on 2023-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0002_autor_socio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='ficha_id',
        ),
        migrations.AddField(
            model_name='socio',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
        ),
    ]
